#!/bin/bash

echo "Starting the script"

echo "isolating object"
./script/magicwand $2,$3 -m binary $1 $4/$5.$6.object.png

echo "triming the image"
./script/autotrim $4/$5.$6.object.png $4/$5.$6.object.png

echo "adding safe borders"
convert -border 15x15 -bordercolor "#000000" $4/$5.$6.object.png $4/$5.$6.object.png

echo "END"